image:
  - ubuntu

platform:
  - x64

services:
  - docker
  
branches:
  except:
    - /.*/

build_script:
  - docker pull quay.io/puteulanus/zsun-builder
  - docker tag quay.io/puteulanus/zsun-builder build
  - mkdir build_dir
  - docker run -v `pwd`/build_dir:/mnt/build_dir build cp -r /root/openwrt /mnt/build_dir/zsun

artifacts:
  - path: build_dir/zsun/targets/ar71xx/generic/*.bin
  - name: images
  
  - path: build_dir/zsun/targets/ar71xx/generic/*.tar.xz
  - name: builder
  
  - path: build_dir/zsun/packages
  - name: packages
  - type: zip
