image:
  - ubuntu

platform:
  - x64

services:
  - docker
  
branches:
  except:
    - /.*/

build_script:
  - docker pull quay.io/puteulanus/zsun-builder
  - docker tag quay.io/puteulanus/zsun-builder build
  - mkdir build_dir
  - docker run -v `pwd`/build_dir:/mnt/build_dir build cp -r /root/openwrt/* /mnt/build_dir/

artifacts:
  - path: build_dir/*
